const qwerty_layout = {
    "a": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "b": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "c": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "d": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "e": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "f": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "g": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "h": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "i": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "j": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "k": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "l": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "m": {
        is_right: true,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "n": {
        is_right: true,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "o": {
        is_right: true,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "p": {
        is_right: true,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "q": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "r": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "s": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "t": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "u": {
        is_right: true,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "v": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "w": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "x": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "y": {
        is_right: true,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
    "z": {
        is_right: false,
        path_fill: preload(),
        path_highlight: preload(),
        path_outline: preload(),
    },
}
